version: '3.8'
services:
  find-my-pet:
    container_name: find-my-pet
    image: reyesi/find-my-pet:latest
    restart: always 
    links:
      - find-my-pet-db
    ports:
      - 8080:8080
    environment:
      DB_PASSWORD: muppet
      EMAIL_USERNAME: your_email@gmail.com
      EMAIL_PASSWORD: email_application_password
      
  find-my-pet-db:
    container_name: find-my-pet-db
    image: mysql:8.0
    restart: always
    volumes:
      - ./init/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: find_my_pet
      MYSQL_ROOT_PASSWORD: muppet
    ports:
      - 3310:3306